"""Download Lucide icons used in the home redesign and emit TS path registry + static SVG files."""
from __future__ import annotations

import json
import re
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ICONS_DIR = ROOT / "src" / "static" / "icons"
REGISTRY_TS = ROOT / "src" / "utils" / "lucideIconPaths.ts"
LUCIDE_VERSION = "0.468.0"
BASE_URL = f"https://unpkg.com/lucide-static@{LUCIDE_VERSION}/icons"

# Lucide icon file name -> app glyph key (SvgIcon `name`, no icon- prefix)
ICONS: dict[str, str] = {
    "brain-circuit": "brain-circuit",
    "megaphone": "megaphone",
    "sparkles": "sparkles",
    "clapperboard": "clapperboard",
    "book-open": "book-open",
    "copy": "copy",
    "lightbulb": "lightbulb",
    "user-round-cog": "user-round-cog",
    "user": "user",
    "crown": "crown",
    "badge-check": "badge-check",
    "contact-round": "contact-2",
    "history": "history",
    "send": "send",
    "badge-plus": "badge-plus",
    "chevron-right": "chevron-right",
    "trending-down": "trending-down",
    "trending-up": "trending-up",
}

# Backward-compatible aliases for existing iconfont keys
ALIASES: dict[str, str] = {
    "notice": "megaphone",
    "agent": "brain-circuit",
    "linggan": "lightbulb",
    "linggan2": "lightbulb",
    "linggan3": "lightbulb",
    "book": "book-open",
    "send2": "send",
    "works": "contact-2",
}


def fetch_svg(icon_file: str) -> str:
    url = f"{BASE_URL}/{icon_file}.svg"
    with urllib.request.urlopen(url, timeout=30) as resp:
        return resp.read().decode("utf-8")


def extract_inner(svg: str) -> str:
    """Keep path/circle/line/polyline/rect elements only (no outer svg wrapper)."""
    inner = re.sub(r"<!--.*?-->", "", svg, flags=re.S)
    m = re.search(r"<svg[^>]*>(.*)</svg>", inner, flags=re.S | re.I)
    if not m:
        raise ValueError("Invalid SVG")
    body = m.group(1).strip()
    body = re.sub(r"\s+", " ", body)
    return body


def main() -> None:
    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    paths: dict[str, str] = {}

    for file_name, key in ICONS.items():
        svg_raw = fetch_svg(file_name)
        inner = extract_inner(svg_raw)
        paths[key] = inner

        mono_svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" '
            'fill="none" stroke="currentColor" stroke-width="2" '
            'stroke-linecap="round" stroke-linejoin="round">'
            f"{inner}</svg>"
        )
        out = ICONS_DIR / f"{key}.svg"
        out.write_text(mono_svg, encoding="utf-8")
        print("wrote", out.relative_to(ROOT))

    all_keys = {**paths}
    for alias, target in ALIASES.items():
        if target in paths:
            all_keys[alias] = paths[target]

    lines = [
        "/** Auto-generated by scripts/export_lucide_icons.py — do not edit manually. */",
        "",
        "export const LUCIDE_ICON_INNER: Record<string, string> = " + json.dumps(all_keys, ensure_ascii=False, indent=2) + ";",
        "",
        "export const LUCIDE_ICON_ALIASES: Record<string, string> = " + json.dumps(ALIASES, ensure_ascii=False, indent=2) + ";",
        "",
        "export function resolveLucideIconName(name: string | undefined | null): string | null {",
        "  const key = (name ?? '').trim()",
        "  if (!key) return null",
        "  if (LUCIDE_ICON_INNER[key]) return key",
        "  const alias = LUCIDE_ICON_ALIASES[key]",
        "  return alias && LUCIDE_ICON_INNER[alias] ? alias : null",
        "}",
        "",
        "export function buildLucideDataUri(name: string, color: string): string | null {",
        "  const resolved = resolveLucideIconName(name)",
        "  if (!resolved) return null",
        "  const inner = LUCIDE_ICON_INNER[resolved]",
        "  const svg =",
        "    `<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"${color}\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\">${inner}</svg>`",
        "  return `data:image/svg+xml,${encodeURIComponent(svg)}`",
        "}",
        "",
    ]
    REGISTRY_TS.write_text("\n".join(lines), encoding="utf-8")
    print("wrote", REGISTRY_TS.relative_to(ROOT))


if __name__ == "__main__":
    main()
